/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Z9bGjFZSVsi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Caudex } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function NavyBlog() {
  return (
    <div className="bg-[#001d3d] text-yellow-300">
      <section className="w-full py-12 md:py-24 lg:py-32 border-b">
        <div className="container space-y-10 xl:space-y-16 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl">Electrical Insights</h1>
              <p className="max-w-[700px] text-yellow-300 md:text-xl">
                Stay up-to-date with the latest news, tips, and trends in the electrical industry.
              </p>
            </div>
          </div>
        </div>
      </section>
      <div className="container grid grid-cols-1 md:grid-cols-[3fr_1fr] gap-8 py-12 md:py-24 px-4 md:px-6">
        <div className="grid gap-8">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-8">
            <div className="group rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-shadow">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Blog Post Image"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }}
              />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-bold group-hover:text-yellow-300 transition-colors">
                  The Importance of Proper Electrical Wiring
                </h3>
                <p className="text-yellow-300 line-clamp-2">
                  Discover the critical role of proper electrical wiring in ensuring the safety and efficiency of your
                  home or business.
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center font-medium text-yellow-300 hover:underline"
                  prefetch={false}
                >
                  Read More
                  <ArrowRightIcon className="ml-1 w-4 h-4" />
                </Link>
              </div>
            </div>
            <div className="group rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-shadow">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Blog Post Image"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }}
              />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-bold group-hover:text-yellow-300 transition-colors">
                  Electrical Safety Tips for Homeowners
                </h3>
                <p className="text-yellow-300 line-clamp-2">
                  Ensure the safety of your home by following these essential electrical safety tips.
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center font-medium text-yellow-300 hover:underline"
                  prefetch={false}
                >
                  Read More
                  <ArrowRightIcon className="ml-1 w-4 h-4" />
                </Link>
              </div>
            </div>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-8">
            <div className="group rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-shadow">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Blog Post Image"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }}
              />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-bold group-hover:text-yellow-300 transition-colors">
                  Upgrading to LED Lighting: Benefits and Considerations
                </h3>
                <p className="text-yellow-300 line-clamp-2">
                  Explore the advantages of upgrading to energy-efficient LED lighting and what to consider during the
                  process.
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center font-medium text-yellow-300 hover:underline"
                  prefetch={false}
                >
                  Read More
                  <ArrowRightIcon className="ml-1 w-4 h-4" />
                </Link>
              </div>
            </div>
            <div className="group rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-shadow">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Blog Post Image"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }}
              />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-bold group-hover:text-yellow-300 transition-colors">
                  The Future of Renewable Energy in the Electrical Industry
                </h3>
                <p className="text-yellow-300 line-clamp-2">
                  Discover the latest trends and advancements in renewable energy and its impact on the electrical
                  industry.
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center font-medium text-yellow-300 hover:underline"
                  prefetch={false}
                >
                  Read More
                  <ArrowRightIcon className="ml-1 w-4 h-4" />
                </Link>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-[#002e5d] rounded-lg p-6 space-y-6">
          <div>
            <h3 className="text-lg font-bold">Categories</h3>
            <div className="mt-4 grid gap-2">
              <Link
                href="#"
                className="inline-flex items-center rounded-md bg-[#001d3d] px-3 py-1 text-sm font-medium text-yellow-300 hover:bg-yellow-300 hover:text-[#001d3d]"
                prefetch={false}
              >
                Home Wiring
              </Link>
              <Link
                href="#"
                className="inline-flex items-center rounded-md bg-[#001d3d] px-3 py-1 text-sm font-medium text-yellow-300 hover:bg-yellow-300 hover:text-[#001d3d]"
                prefetch={false}
              >
                Electrical Safety
              </Link>
              <Link
                href="#"
                className="inline-flex items-center rounded-md bg-[#001d3d] px-3 py-1 text-sm font-medium text-yellow-300 hover:bg-yellow-300 hover:text-[#001d3d]"
                prefetch={false}
              >
                Industry News
              </Link>
              <Link
                href="#"
                className="inline-flex items-center rounded-md bg-[#001d3d] px-3 py-1 text-sm font-medium text-yellow-300 hover:bg-yellow-300 hover:text-[#001d3d]"
                prefetch={false}
              >
                DIY Electrical
              </Link>
            </div>
          </div>
          <div>
            <h3 className="text-lg font-bold">Tags</h3>
            <div className="mt-4 grid gap-2">
              <Link
                href="#"
                className="inline-flex items-center rounded-md bg-[#001d3d] px-3 py-1 text-sm font-medium text-yellow-300 hover:bg-yellow-300 hover:text-[#001d3d]"
                prefetch={false}
              >
                Wiring
              </Link>
              <Link
                href="#"
                className="inline-flex items-center rounded-md bg-[#001d3d] px-3 py-1 text-sm font-medium text-yellow-300 hover:bg-yellow-300 hover:text-[#001d3d]"
                prefetch={false}
              >
                Lighting
              </Link>
              <Link
                href="#"
                className="inline-flex items-center rounded-md bg-[#001d3d] px-3 py-1 text-sm font-medium text-yellow-300 hover:bg-yellow-300 hover:text-[#001d3d]"
                prefetch={false}
              >
                Electrical Codes
              </Link>
              <Link
                href="#"
                className="inline-flex items-center rounded-md bg-[#001d3d] px-3 py-1 text-sm font-medium text-yellow-300 hover:bg-yellow-300 hover:text-[#001d3d]"
                prefetch={false}
              >
                Renewable Energy
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}
