/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KDEvqYYAhJr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"

export function serviceCarousel() {
  return (
    <div className="w-full max-w-6xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <Carousel className="rounded-lg overflow-hidden">
        <CarouselContent>
          <CarouselItem>
            <div className="relative h-[400px] sm:h-[500px] lg:h-[600px]">
              <img
                src="/placeholder.svg"
                alt="Service 1"
                width={1200}
                height={600}
                className="w-full h-full object-cover"
                style={{ aspectRatio: "1200/600", objectFit: "cover" }}
              />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                <div className="text-center text-white">
                  <h3 className="text-2xl font-bold mb-2">Web Development</h3>
                  <p className="text-lg">Our expert team crafts custom websites tailored to your business needs.</p>
                </div>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="relative h-[400px] sm:h-[500px] lg:h-[600px]">
              <img
                src="/placeholder.svg"
                alt="Service 2"
                width={1200}
                height={600}
                className="w-full h-full object-cover"
                style={{ aspectRatio: "1200/600", objectFit: "cover" }}
              />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                <div className="text-center text-white">
                  <h3 className="text-2xl font-bold mb-2">Mobile App Development</h3>
                  <p className="text-lg">Bring your ideas to life with our mobile app development services.</p>
                </div>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="relative h-[400px] sm:h-[500px] lg:h-[600px]">
              <img
                src="/placeholder.svg"
                alt="Service 3"
                width={1200}
                height={600}
                className="w-full h-full object-cover"
                style={{ aspectRatio: "1200/600", objectFit: "cover" }}
              />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                <div className="text-center text-white">
                  <h3 className="text-2xl font-bold mb-2">Digital Marketing</h3>
                  <p className="text-lg">
                    Reach your target audience with our comprehensive digital marketing solutions.
                  </p>
                </div>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="relative h-[400px] sm:h-[500px] lg:h-[600px]">
              <img
                src="/placeholder.svg"
                alt="Service 4"
                width={1200}
                height={600}
                className="w-full h-full object-cover"
                style={{ aspectRatio: "1200/600", objectFit: "cover" }}
              />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                <div className="text-center text-white">
                  <h3 className="text-2xl font-bold mb-2">Branding and Design</h3>
                  <p className="text-lg">Elevate your brand with our creative design and branding services.</p>
                </div>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="relative h-[400px] sm:h-[500px] lg:h-[600px]">
              <img
                src="/placeholder.svg"
                alt="Service 5"
                width={1200}
                height={600}
                className="w-full h-full object-cover"
                style={{ aspectRatio: "1200/600", objectFit: "cover" }}
              />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                <div className="text-center text-white">
                  <h3 className="text-2xl font-bold mb-2">IT Consulting</h3>
                  <p className="text-lg">Get expert guidance and solutions for your technology challenges.</p>
                </div>
              </div>
            </div>
          </CarouselItem>
        </CarouselContent>
        <CarouselPrevious className="absolute left-4 top-1/2 -translate-y-1/2 bg-white/50 hover:bg-white/75 rounded-full p-2 cursor-pointer transition-colors">
          <ChevronLeftIcon className="w-6 h-6 text-gray-700" />
        </CarouselPrevious>
        <CarouselNext className="absolute right-4 top-1/2 -translate-y-1/2 bg-white/50 hover:bg-white/75 rounded-full p-2 cursor-pointer transition-colors">
          <ChevronRightIcon className="w-6 h-6 text-gray-700" />
        </CarouselNext>
      </Carousel>
    </div>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
